package com.xxy.seckill.seckillmanagement.dataobject;

public class XiaoquDAO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.id
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.city
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.date
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.district
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.area
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.xiaoqu
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private String xiaoqu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.price
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoqu.sale
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    private Integer sale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.id
     *
     * @return the value of xiaoqu.id
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.id
     *
     * @param id the value for xiaoqu.id
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.city
     *
     * @return the value of xiaoqu.city
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.city
     *
     * @param city the value for xiaoqu.city
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.date
     *
     * @return the value of xiaoqu.date
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.date
     *
     * @param date the value for xiaoqu.date
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.district
     *
     * @return the value of xiaoqu.district
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.district
     *
     * @param district the value for xiaoqu.district
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.area
     *
     * @return the value of xiaoqu.area
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.area
     *
     * @param area the value for xiaoqu.area
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.xiaoqu
     *
     * @return the value of xiaoqu.xiaoqu
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public String getXiaoqu() {
        return xiaoqu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.xiaoqu
     *
     * @param xiaoqu the value for xiaoqu.xiaoqu
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setXiaoqu(String xiaoqu) {
        this.xiaoqu = xiaoqu == null ? null : xiaoqu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.price
     *
     * @return the value of xiaoqu.price
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.price
     *
     * @param price the value for xiaoqu.price
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoqu.sale
     *
     * @return the value of xiaoqu.sale
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoqu.sale
     *
     * @param sale the value for xiaoqu.sale
     *
     * @mbg.generated Wed Nov 13 14:48:24 CST 2019
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }
}